# Generated by Django 5.1.3 on 2024-12-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliccita_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pizza',
            table='pizzas',
        ),
    ]
