# Generated by Django 5.1.3 on 2024-12-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliccita_app', '0002_alter_pizza_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
    ]
